---
- name: Deploy Web Application
  hosts: webservers
  become: yes

  vars:
    app_src_dir: /home/ubuntu/app
    app_dest_dir: /var/www/html

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy application files
      copy:
        src: "{{ app_src_dir }}/"
        dest: "{{ app_dest_dir }}/"
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
